Map<String,String> ar ={
  "Welcome,":"مرحبا",
  "Total":"السعر",
  "Sign in to Continue":"سجل الدخول للأستمرار",
  "Sign":"سجل",
  "Email":"البريد الألكتروني",
  "Enter Your Email":"أدخل البريد الألكتروني",
  "Password":"كلمة السر",
  "Enter Your Password":"أدخل كلمة السر",
  "Forgot Password?":"هل نسيت كلمة السر؟",
  "SIGN IN":"سجل الدخول",
  "OR":"أو",
  "Sign in with Google":"سجل الدخول باستخدام جوجل",
  "Sign in with Facebook":"سجل الدخول باستخدام فيسبوك",
  "This Field can't be empty":"هذا الحق لا يمكن ان يكون فارغا",
  "Enter Your Name":"أكتب اسمك",
  "Name":"الأسم",
  "Sign Up":"تسجيل",
  "Price":"السعر",
  "Size":"الحجم",
  "Color":"اللون",
  "Details":"التفاصيل",
  "Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer. Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer. Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.":"Nike Dri-FIT هو نسيج بوليستر مصمم لمساعدتك على الحفاظ على الجفاف حتى تتمكن من العمل براحة أكبر لفترة أطول. Nike Dri-FIT هو نسيج بوليستر مصمم لمساعدتك على الحفاظ على الجفاف حتى تتمكن من العمل براحة أكبر لفترة أطول. Nike Dri-FIT هو نسيج بوليستر مصمم لمساعدتك على الحفاظ على الجفاف حتى تتمكن من العمل براحة أكبر لفترة أطول.",
  "Add":"أضافة",
  "Leather Wristwatch":"ساعة يد جلدية",
  "BeoPlay Speaker":"مكبر صوت BeoPlay",
  " Explore":" استكشف",
  " Cart":" السلة",
  " Account":" الحساب",
  "Categories":"الأقسام",
  "Best Selling":"الأفضل مبيعا",
  "See all":"تصفح الكل",
  "Men":"رجال",
  "Gadgets":"أدوات",
  "Gaming":"ألعاب",
  "Women":"حريمي",
  "Devices":"أجهزة",
  "are you sure you want to delete it?":"هل انت متأكد أنك تريد حذف هذا المنتج؟",
  "CHECKOUT":"الدفع",
  "Edit Profile":"تعديل الصفحة الشخصية",
  "Shipping Address":"عناوين الشحن",
  "Order History":"تاريخ الطلب",
  "Cards":"البطاقات",
  "Notifications":"الأشعارات",
  "Log Out":"تسجيل الخروج",
  "Change Language":"تغيير اللغة",
  "Choose language":"أختار اللغة",
  "Cart is Empty":"السلة فارغة",
  "Standard Delivery":"التسليم القياسي",
  "Next Day Delivery":"التسليم في اليوم التالي",
  "Nominated Delivery":"التسليم المعين",
  "Order will be delivered between 3 - 5 business days":"سيتم توصيل الطلب ما بين 3 - 5 أيام عمل",
  "Place your order before 6pm and your items will be delivered the next day":"قدم طلبك قبل الساعة 6 مساءً وسيتم توصيل أغراضك في اليوم التالي",
  "Pick a particular date from the calendar and order will be delivered on selected date":"اختر تاريخًا معينًا من التقويم وسيتم تسليم الطلب في التاريخ المحدد",
  "Delivery":"التوصيل",
  "Remove":"حذف",
  "Cancel":"الغاء",
  "Billing address is the same as delivery address":"عنوان الفواتير هو نفسه عنوان التسليم",
  "Street 1":"شارع 1",
  "Street 2":"شارع 2",
  "City":"المدينه",
  "State":"الولاية",
  "Country":"الدولة",
  "Address":"العنوان",
  "Summary":"الملخص",
  "Total price":"السعر النهائي",
  "Total Price":"السعر النهائي",
  "Please fill all data !!":"من فضلك املأ جميع البيانات !!",
  "Something went error":"حدث خطأ !",
  "Updated successfully":"تم تحديث البيانات بنجاح",
  "Update":"تحديث",
  "Added Successfully":"تمت الاضافة بنجاح",
  "Write a New password if you want to change it":"اكتب كلمة السر الجديدة اذا كنت تريد تغييرها",
  "in Transit":"في مرحلة انتقالية",
  "Address : ":"العنوان : ",
  "Already in cart":"بالفعل في السلة !",
  " Favourite":" المفضلة",
  "Order is Empty":"لا يوجد طلبات",
  "Shipping is Empty":"لا يوجد عناوين لك",
  "Skip":"تخطي",
  "Next":"التالي",
  "Done":"الانتهاء",
  "Trans":"نوع التوصيل",
  "Rezk-Store":"متجر الرزق",
  "Favourite is Empty":"لا يوجد منتجات في مفضلتك",
  "Products":"المنتجات",
};