Map<String,String> en ={
  "Welcome,":"Welcome,",
  "Sign in to Continue":"Sign in to Continue",
  "Sign":"Sign",
  "Email":"Email",
  "Password":"Password",
  "Enter Your Password":"Enter Your Password",
  "Enter Your Email":"Enter Your Email",
  "Forgot Password?":"Forgot Password?",
  "SIGN IN":"SIGN IN",
  "OR":"OR",
  "Sign in with Google":"Sign in with Google",
  "Sign in with Facebook":"Sign in with Facebook",
  "This Field can't be empty":"This Field can't be empty",
  "Enter Your Name":"Enter Your Name",
  "Name":"Name",
  "Sign Up":"Sign Up",
  "Price":"Price",
  "Size":"Size",
  "Color":"Color",
  "Details":"Details",
  "Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer. Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer. Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.":"Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer. Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer. Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.",
  "Add":"Add",
  "Added Successfully":"Added Successfully",
  " Explore":" Explore",
  " Cart":" Cart",
  " Account":" Account",
  "Categories":"Categories",
  "Best Selling":"Best Selling",
  "See all":"See all",
  "Men":"Men",
  "Gadgets":"Gadgets",
  "Gaming":"Gaming",
  "Women":"Women",
  "Devices":"Devices",
  "are you sure you want to delete it?":"Are you sure you want to delete it?",
  "CHECKOUT":"CHECKOUT",

  "Edit Profile":"Edit Profile",
  "Products":"Products",
  "Shipping Address":"Shipping Address",
  "Order History":"Order History",
  "Cards":"Cards",
  "Notifications":"Notifications",
  "Log Out":"Log Out",
  "Change Language":"Change Language",
  "Choose language":"Choose language",
  "Cart is Empty":"Cart is Empty",
  "Standard Delivery":"Standard Delivery",
  "Next Day Delivery":"Next Day Delivery",
  "Nominated Delivery":"Nominated Delivery",
  "Order will be delivered between 3 - 5 business days":"Order will be delivered between 3 - 5 business days",
  "Place your order before 6pm and your items will be delivered the next day":"Place your order before 6pm and your items will be delivered the next day",
"Pick a particular date from the calendar and order will be delivered on selected date":"Pick a particular date from the calendar and order will be delivered on selected date",
  "Delivery":"Delivery",
  "Remove":"Remove",
  "Cancel":"Cancel",
  "Billing address is the same as delivery address":"Billing address is the same as delivery address",
  "Street 1":"Street 1",
  "Street 2":"Street 2",
  "City":"City",
  "State":"State",
  "Country":"Country",
  "Address":"Address",
  "Summary":"Summary",
  "Total":"Total",
  "Total Price":"Total Price",
  "Please fill all data !!":"Please fill all data !!",
  "Something went error":"Something went error",
  "Updated successfully":"Updated successfully",
  "Update":"Update",
  "Write a New password if you want to change it":"Write a New password if you want to change it",
  "in Transit":"in Transit",
  "Address : ":"Address : ",
  "Already in cart":"Already in cart",
  " Favourite":" Favourite",
  "Order is Empty":"Order is Empty",
  "Shipping is Empty":"Shipping is Empty",
  "Skip":"Skip",
  "Next":"Next",
  "Done":"Done",
  "Trans":"Delivery type",
  "Rezk-Store":"Rezk-Store",
  "Favourite is Empty":"Favourite is Empty",
  "Removed from favourite successfully":"Removed from favourite successfully",
  "Added to favourite successfully":"Added to favourite successfully",
};